name: Release APM Audit

on:
  push:
    tags:
      - 'v*.*.*'
      - 'anvil-*-stable-v*.*.*'

jobs:
  audit:
    uses: ./.github/workflows/_apm-audit.yml
    with:
      trigger: release
      base_ref: ${{ github.event.before }}
      head_ref: ${{ github.sha }}
    permissions:
      contents: read
      pull-requests: write
